server:
  port: 80

spring:
    datasource:
#    mysql.c02i0r3jxxrw.us-east-2.rds.amazonaws.com
        name: test
        url: jdbc:mysql:///mydb?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    velocity:
        suffix: .html
       # date-tool-attribute: date
mybatis:
  mapper-locations: classpath:com/fc/toutiaonews/dao/*.xml
  type-aliases-package: com.fc.toutiaonews.domain


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
#    com.llt.smzdm.dao: DEBUG
    com.llt.smzdm.asyncevent.EventDispater: error
